In [8]:
# import Numpy package
import numpy as np

# Creating Array from Python List
my_list = [1,2,3,4]

# Converting Python list to Numpy Array
arr = np.array(my_list)

In [9]:
# Printing Out Array
arr

array([1, 2, 3, 4])

In [10]:
# To get Array Dimensions. Output (4,) means 4 rows & zero columns 
arr.shape

(4,)

In [13]:
arr2 = np.array([[1,2,3], 
                 [4,5,6]])

arr2.shape     # Output 2,3 indicates 2 rows and 3 columns

(2, 3)

In [18]:
# We can change the shape of an array by two ways:
# Method 1 is In place change where array is directly modified

arr2.shape = (3,2)

arr2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [24]:
# Method 2 creates an new array and old array remains unmodified by using reshape method. 
# reshape(array_name, (array_dimensions))

new_arr = np.reshape(arr2,(2,3))

new_arr  #Creates a new array 

array([[1, 2],
       [3, 4],
       [5, 6]])

In [25]:
arr2   #old orray values are unmodified.

array([[1, 2],
       [3, 4],
       [5, 6]])